[workspace]

members = [
    "test-wasi",
    "test-authn",
    "test-authz",
    "test-admission",
    "test-admission-mut",
    "test-admission-mut-helper",
    "test-wapc",
    "test-kubewarden-mut",
]
